### ISSUE TITLE
Add Counter and Limits to Content As Well

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/Limit-Post-Titles#1]
When using the plugin in concert with https://github.com/hwdsbcommons/reveal-js-presentations limiting the number of characters that appear on a slide becomes important.

**Comment by r-a-y** [comment]
Works locally on my end.

Did you configure the settings under "Settings > Limit Post Titles" and select "Slides" for the post type?

Edit: Misread your issue title.  You want to limit by content as well?

**Comment by mrjarbenne** [comment]
Exactly. Take a look at this site:

https://570.commons.hwdsb.on.ca/presentation/announcements/

The second slide (footloose) shows the issue. Users are adding content but not checking to see if it's legible. It overflows off the slide. 

I need to be able to add a character limit to slide content in a similar way that the plugin allows for titles. 

![img_6315](https://user-images.githubusercontent.com/480667/30236625-6cb0d0d0-94eb-11e7-990b-e73bef563af6.PNG)

**Comment by r-a-y** [comment]
Gotcha, I created a new issue under the Reveal JS Presentations repo - https://github.com/hwdsbcommons/reveal-js-presentations/issues/9.

Going to close this out to prevent forking the discussion.
